# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-31 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='choice1',
        ),
    ]
