# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-09 13:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question_manager', '0004_auto_20160505_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q1', to='question_manager.Question')),
                ('q2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q2', to='question_manager.Question')),
                ('q3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q3', to='question_manager.Question')),
                ('q4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q4', to='question_manager.Question')),
                ('q5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q5', to='question_manager.Question')),
                ('requested_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_score', to='question_manager.Score')),
                ('requested_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_user', to=settings.AUTH_USER_MODEL)),
                ('starter_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starter_score', to='question_manager.Score')),
                ('starter_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starter_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
