# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-28 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_manager', '0010_auto_20160510_1154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': 'مسابقه', 'verbose_name_plural': 'مسابقه\u200cها'},
        ),
    ]
