# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-29 05:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('question_manager', '0011_auto_20160528_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, '\u0627\u0645\u062a\u06cc\u0627\u0632'), (1, '\u0628\u0631\u062f \u0645\u062a\u0648\u0627\u0644\u06cc'), (2, '\u0628\u0627\u0632\u06cc'), (3, '\u0628\u0631\u062f')], max_length=1)),
                ('time', models.IntegerField()),
                ('time_unit', models.IntegerField(choices=[(0, '\u0633\u0627\u0639\u062a'), (1, '\u0631\u0648\u0632'), (2, '\u0647\u0641\u062a\u0647')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 29, 5, 53, 26, 247737, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
