# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-29 06:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question_manager', '0012_auto_20160529_0553'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='achievement',
            options={'verbose_name': '\u062f\u0633\u062a\u0627\u0648\u0631\u062f', 'verbose_name_plural': '\u062f\u0633\u062a\u0627\u0648\u0631\u062f'},
        ),
        migrations.AddField(
            model_name='achievementuser',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_manager.Achievement'),
        ),
        migrations.AddField(
            model_name='achievementuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
