# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-29 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_manager', '0015_auto_20160529_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='amount',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
