# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-29 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_manager', '0016_auto_20160529_0608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'verbose_name': '\u062f\u0633\u062a\u0627\u0648\u0631\u062f', 'verbose_name_plural': '\u062f\u0633\u062a\u0627\u0648\u0631\u062f\u0647\u0627'},
        ),
        migrations.AlterField(
            model_name='achievement',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='\u0645\u06cc\u0632\u0627\u0646'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='time',
            field=models.IntegerField(default=0, verbose_name='\u0628\u0627\u0632\u0647\u200c\u06cc \u0632\u0645\u0627\u0646\u06cc'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='time_unit',
            field=models.IntegerField(choices=[(0, '\u0633\u0627\u0639\u062a'), (1, '\u0631\u0648\u0632'), (2, '\u0647\u0641\u062a\u0647')], verbose_name='\u0646\u0648\u0639 \u0632\u0645\u0627\u0646'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='type',
            field=models.IntegerField(choices=[(0, '\u0627\u0645\u062a\u06cc\u0627\u0632'), (1, '\u0628\u0631\u062f \u0645\u062a\u0648\u0627\u0644\u06cc'), (2, '\u0628\u0627\u0632\u06cc'), (3, '\u0628\u0631\u062f')], max_length=1, verbose_name='\u0646\u0648\u0639 \u062f\u0633\u062a\u0627\u0648\u0631\u062f'),
        ),
    ]
