# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-27 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_account_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='test',
            field=models.CharField(default='t', max_length=40, unique=True),
        ),
    ]
