# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-02 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20160330_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='country',
            field=models.CharField(choices=[(b'IR', b'\xd8\xa7\xdb\x8c\xd8\xb1\xd8\xa7\xd9\x86'), (b'US', b'\xd8\xa2\xd9\x85\xd8\xb1\xdb\x8c\xda\xa9\xd8\xa7')], default=b'IR', max_length=3),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[(b'M', b'\xd9\x85\xd8\xb1\xd8\xaf'), (b'F', b'\xd8\xb2\xd9\x86')], default=b'M', max_length=1),
        ),
    ]
